// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoCAPI.Data;

#nullable disable

namespace PoCAPI.Migrations
{
    [DbContext(typeof(ordersDbContext))]
    [Migration("20230407181041_ordersDb")]
    partial class ordersDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Orders")
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PoCAPI.Models.Orders", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ammount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketPrice")
                        .HasColumnType("int");

                    b.Property<int>("TotalOrderPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("orders", "Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e049fc80-8e4a-4b2a-ab8e-7288ed0e0e2d"),
                            Ammount = 1,
                            ArrivalTime = new DateTime(2023, 4, 2, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerEmail = "Williamsorensen1996@gmail.com",
                            CustomerID = "095d470e-1f5a-477f-b0dd-d11edac2deac",
                            DepartureTime = new DateTime(2023, 4, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "DEF456",
                            TicketPrice = 200,
                            TotalOrderPrice = 200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
